[package]
name = "photofinish"
version = "1.0.3"
edition = "2018"

[dependencies]
toml = "0.5"
clap = "3.0.7"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
