# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: Apache-2.0

name: Build and Push Docker

# Run workflow on tags starting with v (eg. v2, v1.2.0)
on:
  push:
    tags:        
      - v*

jobs:
  Deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # v2
        with:
          push: true # Will only build if this is not here
          tags: |
            ghcr.io/${{ github.repository }}:latest
