name: Release binary

on:
  push:
    tags:        
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/release/photofinish
