# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: Apache-2.0

name: Release binary

on:
  push:
    tags:        
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Build
      run: cargo build --release
    - name: Compress action step
      uses: a7ul/tar-action@ed9cbd44fc9276db29ea2fb1f8adf3d7e0691589 # v1.2.0
      id: compress
      with:
        command: c
        cwd: ./target/release/
        files: |
          ./photofinish
        outPath: photofinish_linux_x86_64.tar.gz
    - name: Release
      uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
      with:
        files: ./photofinish_linux_x86_64.tar.gz
