name: Release binary

on:
  push:
    tags:        
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
    - name: Build
      run: cargo build --release
    - name: Compress action step
      uses: a7ul/tar-action@6b2b13625a2e286a0a04950810139961bf8ce00d # v1.1.0
      id: compress
      with:
        command: c
        cwd: ./target/release/
        files: |
          ./photofinish
        outPath: photofinish_linux_x86_64.tar.gz
    - name: Release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
      with:
        files: ./photofinish_linux_x86_64.tar.gz
